//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micro_Ondas.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Tipos
    {
        public int ID { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Nome:")]
		public string Nome { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Instruções:")]
		public string Instruções { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Tempo (em segundos):")]
		[Range(typeof(Int32), "1", "120", ErrorMessage = "*Digite um número entre 1(segundo) e 120(segundos)!")]
		public int Tempo { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Potência:")]
		[Range(typeof(Int32), "1", "10", ErrorMessage = "*Digite uma potência entre 1 e 10!")]
		public int Potencia { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Caracter:")]
		[StringLength(1, MinimumLength = 1, ErrorMessage = "Digite apenas 1 caracter")]
		public string Caracter { get; set; }
    }
}
